### ISSUE TITLE
footer note for forum site

### ISSUE THREAD

**Issue by andatoshiki** [white-windmills/lostark-forum#1]

**Comment by hs-07** [comment]
hey @andatoshiki , i found this project very interesting and would like to show my enthusiasm in working over it.
can u explain a bit about the issue,

**Comment by andatoshiki** [comment]
> hey @andatoshiki , i found this project very interesting and would like to show my enthusiasm in working over it.
can u explain a bit about the issue,

Hi Shukla! Sorry for the reply, this is issue is currently resolved, I think I miss added a co-contributer to this issue or you just want to jump in and help, if the former case is not true I apologize, we currently need some quick `css` style fixes, we are welcomed for your help :), I'll keep you notified when we need third party expert like you!
